### ISSUE TITLE
CodeDeploy service not running - dependency version conflict

### ISSUE THREAD

**Issue by tomharvey** [continuousphp/aws-codedeploy-agent#9]
The log shows a looping output of the below:

```
2016-10-20T17:43:02 INFO  [codedeploy-agent(4768)]: master 4768: Spawned child 1/1
2016-10-20T17:43:02 ERROR [codedeploy-agent(17676)]: Plugin codedeploy could not be loaded: Unable to activate codedeploy-commands-1.0.0, because aws-sdk-core-2.3.17 conflicts with aws-sdk-core (~> 2.6.11).
2016-10-20T17:43:02 ERROR [codedeploy-agent(17676)]: booting child: error during start or run: Gem::ConflictError - Unable to activate codedeploy-commands-1.0.0, because aws-sdk-core-2.3.17 conflicts with aws-sdk-core (~> 2.6.11) - /usr/local/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2104:in `raise_if_conflicts'
/usr/local/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1282:in `activate'
/usr/local/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems.rb:198:in `rescue in try_activate'
/usr/local/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems.rb:195:in `try_activate'
/usr/local/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
/usr/local/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/opt/download-codedeploy/lib/instance_agent/plugins/codedeploy/codedeploy_control.rb:1:in `<top (required)>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/register_plugin.rb:15:in `require_relative'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/register_plugin.rb:15:in `<top (required)>'
/usr/local/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:16:in `block in load_plugins'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:12:in `each'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:12:in `load_plugins'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:28:in `prepare_run'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:64:in `block in prepare_run_with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:55:in `with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:63:in `prepare_run_with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:20:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:206:in `block in spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:283:in `block (2 levels) in replace_terminated_children'
/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `call'
/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `block in create_with_logging_context'
2016-10-20T17:43:02 INFO  [codedeploy-agent(4768)]: master 4768: Received CHLD - cleaning dead child process
2016-10-20T17:43:02 INFO  [codedeploy-agent(4768)]: master 4768: been told to replace child 17676
2016-10-20T17:43:02 INFO  [codedeploy-agent(4768)]: master 4768: not enough child processes running - missing at least 1 - respawning
```

I was hoping that this cookbook would take into account that the issue reported against the CodeDeploy agent in https://github.com/aws/aws-codedeploy-agent/issues/61 and it does ... maybe, but has an issue of its own.

I'll test this on Ubuntu Xenial and confirm if it exists there as well.

Reproducing the error is a case of `kitchen converge && kitchen verify` which verifies, but on logging into the machine the agent is just in a respawning loop and does not receive signals from AWS CodeDeploy.

**Comment by tomharvey** [comment]
Tested other distributions and it seems that this is an error across the board. Raised a separate issue to call out the incorrectly passing test.

Looks like a dependancy issue with aws-sdk-core version being installed.

**Comment by rberger** [comment]
Having the same problem on Ubuntu 14.04

**Comment by tomharvey** [comment]
@rberger Note that the issue with code deploy agent https://github.com/aws/aws-codedeploy-agent/issues/61 is now resolved. This should make your life easier. I've yet to re-check if this cookbook works again on ubuntu 14.04

**Comment by Pierozi** [comment]
Thanks your contribution is in last release `0.7.0` soon on chef supermarket.
